config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "tasks#index", as: :tasks
  get "/new", to: "tasks#new", as: :new
  get "/:id", to: "tasks#show", as: :show
  post "/", to: "tasks#create"
  get '/:id/edit', to: "tasks#edit", as: :edit
  patch '/:id', to: "tasks#update", as: :task
  delete "/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed == false
      @details = "This task is  not completed yet"
    else
      @details = "This task is completed"
    end
  end

  def new
    @task = Task.new
    # you need to give an empty shell to your form_for!
  end

  def create
    task = Task.create(task_params)
    redirect_to show_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task
  end

  def destroy

    # fetch restaurant to destroy from DB
    @task = Task.find(params[:id])

    # destroy record
    @task.destroy

    # redirect to index
    redirect_to tasks_path

  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <input type="checkbox" <%= "checked" if task.completed %>> <%= link_to task.title, show_path(task) %> <%= link_to raw("<i class='fa fa-trash'></i>"), destroy_path(task), method: :delete %>
    </li>
  <% end %>
</ul>
<%= link_to "+ Add a new task", new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="top">
  <h1><%= @task.title %></h1>
  <button><i class="fa fa-edit"></i><%= link_to "Edit task", edit_path %></button>
</div>
<div class="details">
  <h3><%= @task.details %></h3>
</div>

<p><input type="checkbox" <%= "checked" if @task.completed %>><%= @details %></p>
<button><%= link_to "Back", tasks_path %></button>